# Generated by Django 4.2 on 2024-07-04 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published'], 'verbose_name': 'imagen', 'verbose_name_plural': 'imagenes'},
        ),
    ]
