# Generated by Django 4.2 on 2024-07-04 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0002_alter_post_options_alter_posttranslation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published'], 'verbose_name': 'Historia', 'verbose_name_plural': 'Historias'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
    ]
