# Generated by Django 4.2 on 2024-07-11 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
